name: technobudo
favicon: null
layout_spectrum: 0.25588
typography_spectrum: 0.5049
title: Flow science and optimal human performance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffafa'
    - '#90340e'
    - '#145166'
    - '#1b697e'
    - '#cc9e95'
  brandStrength: 0.42638820642605424
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
