name: technobudo
favicon: null
layout_spectrum: 0.2585642153862864
typography_spectrum: 0.9250411174725741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.42638820642605424
  lightness: 0.8199545464012772
  saturation: 0.7488910239189863
  rhythmicContrast: 0.6421147207729518
purpose: []
