name: technobudo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00294
title: Flow science and optimal human performance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#c6c6c6'
    - '#fccd07'
    - '#a35021'
    - '#202120'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
