name: technobudo
favicon: null
layout_spectrum: 0.00294
typography_spectrum: 0.5049
title: Flow science and optimal human performance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#c6c6c6'
    - '#fccd07'
    - '#a35021'
    - '#202120'
  brandStrength: 0.42638820642605424
  lightness: 0.8199545464012772
  saturation: 0.7488910239189863
  rhythmicContrast: 0.6421147207729518
purpose: []
